server:
  port: 9001

spring:
  application:
    name: CamundaOrchestrationApplication
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000/oauth2/jwks
  data:
    redis:
      host: localhost
      port: 6379
      password:
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      show-sql: true
  datasource:
      url: jdbc:postgresql://localhost:5432/camunda?currentSchema=orchestration
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver

dubbo:
  application:
    logger: slf4j
    name: CamundaOrchestrationApplication
  registry:
    address: nacos://localhost:8848
  protocol:
    name: tri
    port: 50052
