server:
  port: 9000

spring:
  application:
    name: CamundaOrchestrationAuthApplication
  authorization:
  #  keytool -genkeypair -alias co -keyalg RSA -keysize 2048 -storetype PKCS12 -keystore keystore.p12 -validity 3650
    jwt:
      key-store: classpath:keystore.p12
      key-store-password: password
      key-alias: co
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks
  jpa:
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  datasource:
      url: jdbc:postgresql://localhost:5432/camunda?currentSchema=orchestration
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver

dubbo:
  application:
    logger: slf4j
    name: CamundaOrchestrationApplication
    serialize-check-status: DISABLE
  registry:
    address: nacos://localhost:8848
  protocol:
    name: tri
    port: 50052

logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: DEBUG