server:
  port: 9000

spring:
  data:
    redis:
      host: localhost
      port: 6379
      password:
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      show-sql: true
  datasource:
      url: jdbc:postgresql://localhost:5432/camunda?currentSchema=orchestration
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver
  application:
    name: CamundaOrchestrationApplication
    security:
      secret-key: 686B633834416E396D7436753879382F423F4428482B4C6250655367566B5970
      expiration: 86400000 # 1 day in ms
      refresh-token:
        expiration: 1296000000 # 15 days in ms

dubbo:
  application:
    logger: slf4j
    name: CamundaOrchestrationApplication
  registry:
    address: nacos://localhost:8848
  protocol:
    name: tri
    port: 50052
